# Generated by Django 5.2.5 on 2025-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturaCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_camara', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
