# Generated by Django 5.2.5 on 2025-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TemperaturaCamara',
            new_name='TemperaturaCamaras',
        ),
        migrations.AlterModelTable(
            name='temperaturacamaras',
            table='temperatura_camaras',
        ),
    ]
