# Generated by Django 5.2.5 on 2025-08-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0002_temperatura_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperatura',
        ),
    ]
