# Generated by Django 5.2.5 on 2025-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0003_delete_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturacamaras',
            name='alerta_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
