# Generated by Django 5.1.15 on 2026-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0004_temperaturacamaras_alerta_enviada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_camara', models.IntegerField(unique=True)),
                ('temp_min', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
            ],
            options={
                'db_table': 'configuracion_camaras',
            },
        ),
        migrations.AddField(
            model_name='temperaturacamaras',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturacamaras',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
    ]
