# Generated by Django 5.1.15 on 2026-08-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0005_configuracioncamara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncamara',
            name='nombre',
            field=models.CharField(default='Cámara Principal', max_length=50),
        ),
    ]
