# Generated by Django 5.1.15 on 2026-08-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0006_configuracioncamara_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncamara',
            name='mantenimiento_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
